In [ ]:
#eda feature scaling(we nee sklearner for removing the outliers and other operations
!pip install sklearn;

Collecting sklearn
  Downloading sklearn-0.0.post12.tar.gz (2.6 kB)
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [12]:
#NORMLIZATION
a=sns.load_dataset('titanic')
a

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [11]:
a.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [16]:
# here we can see that there are sum null values
#before going toward the normalization lets fill this stuff
anew=a
anew['age']=anew['age'].fillna(a['age'].mean)
anew['deck']=anew['deck'].fillna("D")
anew['embarked']=anew['embarked'].fillna("C")
anew['embark_town']=anew['embark_town'].fillna("Southampton")
anew.isnull().sum()
#now we have removed all null values

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

In [17]:
#lets check which column is not normnlyy distributed and lets work on it
anew.describe()

         survived      pclass       sibsp       parch        fare
count  891.000000  891.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642    0.523008    0.381594   32.204208
std      0.486592    0.836071    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.000000    0.000000    0.000000
25%      0.000000    2.000000    0.000000    0.000000    7.910400
50%      0.000000    3.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000    8.000000    6.000000  512.329200

In [21]:
#we should work on sibsp,parch and fare column
#creating a new dataframe
df=anew[['sibsp','parch','fare']]
df.head(10)

   sibsp  parch     fare
0      1      0   7.2500
1      1      0  71.2833
2      0      0   7.9250
3      1      0  53.1000
4      0      0   8.0500
5      0      0   8.4583
6      0      0  51.8625
7      3      1  21.0750
8      0      2  11.1333
9      1      0  30.0708

In [22]:
#here calling min max scaler
scaler=MinMaxScaler()
new_df=scaler.fit_transform(df.head(20))#fit transform convert values to 0 to1 values using normalization formula
new_df

array([[2.50000000e-01, 0.00000000e+00, 3.90269489e-04],
       [2.50000000e-01, 0.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.09275457e-02],
       [2.50000000e-01, 0.00000000e+00, 7.16144512e-01],
       [0.00000000e+00, 0.00000000e+00, 1.28788931e-02],
       [0.00000000e+00, 0.00000000e+00, 1.92527744e-02],
       [0.00000000e+00, 0.00000000e+00, 6.96826172e-01],
       [7.50000000e-01, 2.00000000e-01, 2.16209297e-01],
       [0.00000000e+00, 4.00000000e-01, 6.10116097e-02],
       [2.50000000e-01, 0.00000000e+00, 3.56640748e-01],
       [2.50000000e-01, 2.00000000e-01, 1.47912136e-01],
       [0.00000000e+00, 0.00000000e+00, 3.01678315e-01],
       [0.00000000e+00, 0.00000000e+00, 1.28788931e-02],
       [2.50000000e-01, 1.00000000e+00, 3.75439248e-01],
       [0.00000000e+00, 0.00000000e+00, 9.82230250e-03],
       [0.00000000e+00, 0.00000000e+00, 1.36984591e-01],
       [1.00000000e+00, 2.00000000e-01, 3.41876072e-01],
       [0.00000000e+00, 0.00000000e+00, 9.01522519e-02],
       [2.50000000e-01, 0.00000000e+00, 1.68206150e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [29]:
mydata=pd.read_csv("/content/house_price_regression_dataset.csv")
#mydata.head(200)
#detection of an outlier using function

def detection(mydata):
  detected=[]#creating dummy array to save  outlier values

  mydata_std=np.std(mydata)#std deviation
  mydata_mean=np.mean(mydata)#mean

  cutoff=mydata_std*3#cutoff to see ehichg is outlier


#cutoff ranges
  lower_range=mydata_mean-cutoff
  upper_range=mydata_mean+cutoff

  #to find outliers
  for i in mydata:
    if i>upper_range or i<lower_range:
      detected.append(i)
  return detected

In [28]:
mydata.head(200)

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,2.623829e+05
1,4272,3,3,2016,4.753014,1,6,9.852609e+05
2,3592,1,2,2016,3.634823,0,9,7.779774e+05
3,966,1,2,1977,2.730667,1,8,2.296989e+05
4,4926,2,1,1993,4.699073,0,8,1.041741e+06
...,...,...,...,...,...,...,...,...
195,4143,1,2,1984,2.723665,1,8,8.451416e+05
196,2549,5,3,2015,4.374704,2,3,6.562232e+05
197,4223,1,1,2012,2.575251,1,9,8.846777e+05
198,3608,1,2,1972,4.729693,0,9,7.757732e+05
199,4590,1,3,1958,2.768017,0,2,9.188937e+05